# Generated by Django 5.0.4 on 2024-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('numIterations', models.IntegerField()),
                ('stepSize', models.IntegerField()),
                ('rowLength', models.IntegerField()),
                ('rows', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DataModelOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.JSONField()),
                ('yield_value', models.FloatField()),
                ('growth', models.FloatField()),
                ('water', models.FloatField()),
                ('overlap', models.IntegerField()),
                ('map', models.JSONField()),
                ('boundary', models.JSONField()),
                ('weed', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DataModelOutputDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.JSONField()),
                ('yield_value', models.JSONField()),
                ('growth', models.JSONField()),
                ('water', models.JSONField()),
                ('overlap', models.JSONField()),
                ('map', models.JSONField()),
                ('boundary', models.JSONField()),
                ('weed', models.JSONField()),
            ],
        ),
    ]
