# Generated by Django 5.1 on 2024-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="SimulationPreset",
        ),
    ]
