# Generated by Django 5.0.4 on 2024-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodeloutput',
            name='time',
            field=models.TimeField(),
        ),
    ]
