# Generated by Django 5.0.4 on 2024-09-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0002_alter_datamodeloutput_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('W_max', models.FloatField()),
                ('H_max', models.FloatField()),
                ('k', models.FloatField()),
                ('n', models.IntegerField()),
                ('max_moves', models.IntegerField()),
                ('Yield', models.FloatField()),
                ('size_per_plant', models.FloatField()),
                ('row_distance', models.FloatField()),
                ('column_distance', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datamodelinput',
            name='rows',
        ),
        migrations.CreateModel(
            name='RowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantType', models.CharField(max_length=100)),
                ('plantingType', models.CharField(max_length=100)),
                ('stripWidth', models.IntegerField()),
                ('rowSpacing', models.IntegerField()),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simapp.datamodelinput')),
            ],
        ),
    ]
