# Generated by Django 5.0.4 on 2024-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0003_plant_remove_datamodelinput_rows_rowdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodelinput',
            name='numIterations',
        ),
        migrations.AddField(
            model_name='rowdetail',
            name='numIterations',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
