# Generated by Django 5.1 on 2024-09-12 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simapp", "0003_datamodeloutput_rename_datamodel_datamodelinput"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datamodelinput",
            name="data",
        ),
        migrations.RemoveField(
            model_name="datamodeloutput",
            name="data",
        ),
    ]
