# Generated by Django 5.0.4 on 2024-10-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0004_remove_datamodelinput_numiterations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_mode', models.BooleanField(default=False)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simapp.datamodelinput')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_index', models.IntegerField()),
                ('param_value', models.FloatField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='simapp.simulation')),
            ],
        ),
        migrations.DeleteModel(
            name='DataModelOutputDetails',
        ),
        migrations.RemoveField(
            model_name='datamodeloutput',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='datamodeloutput',
            name='time',
        ),
        migrations.RemoveField(
            model_name='datamodeloutput',
            name='weed',
        ),
        migrations.RemoveField(
            model_name='rowdetail',
            name='numIterations',
        ),
        migrations.AlterField(
            model_name='rowdetail',
            name='input_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='simapp.datamodelinput'),
        ),
        migrations.AddField(
            model_name='datamodeloutput',
            name='iteration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='simapp.simulationiteration'),
            preserve_default=False,
        ),
    ]
