# Generated by Django 5.0.4 on 2024-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0005_simulation_simulationiteration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='input_data',
            new_name='input',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='testing_mode',
        ),
        migrations.AddField(
            model_name='simulation',
            name='tag',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
