# Generated by Django 5.0.4 on 2024-10-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0008_simulation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_value', models.FloatField()),
                ('test_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='simulationiteration',
            name='simulation',
        ),
        migrations.AddField(
            model_name='datamodelinput',
            name='simName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodelinput',
            name='testingKey',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodelinput',
            name='testingMode',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodelinput',
            name='testingValue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodeloutput',
            name='date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodeloutput',
            name='weed',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='test',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationiteration',
            name='input',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='simapp.datamodelinput'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulationiteration',
            name='iteration_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationiteration',
            name='param_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
    ]
