# Generated by Django 5.0.4 on 2024-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0009_test_remove_simulationiteration_simulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelinput',
            name='testingMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datamodelinput',
            name='testingValue',
            field=models.FloatField(default=None, null=True),
        ),
    ]
