# Generated by Django 5.0.4 on 2024-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0010_alter_datamodelinput_testingmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelinput',
            name='testingKey',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datamodelinput',
            name='testingMode',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
