# Generated by Django 5.0.4 on 2024-10-14 20:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0012_weather_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.CharField(max_length=100, default='2024-01-01'),  # Example default date, adjust as needed
        ),
        migrations.AddField(
            model_name='weather',
            name='rain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
