# Generated by Django 5.0.4 on 2024-10-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0017_alter_weather_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
