# Generated by Django 5.0.4 on 2024-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0019_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodeloutput',
            name='time_needed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
