# Generated by Django 5.0.4 on 2024-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0020_datamodeloutput_time_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodeloutput',
            name='yield_value',
            field=models.FloatField(null=True),
        ),
    ]
